version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"
    env_file:
      - docker.env
  dynamodb:
    image: "cnadiminti/dynamodb-local"
    ports:
    - "8000:8000"
    volumes:
    - ./data:/dynamodb_local_db